#Para leer base de Escuadrón Básico Territorial

library(tidyverse)
library(stringr)


ebt <- readxl::read_xlsx('ENERO. BASE DE DATOS DE PRODUCTIVIDAD EBT. INTELIGENCIA.xlsx', range = 'B1:DT57') %>% 
  mutate(FECHA = as.Date(FECHA)) %>% filter(!is.na(DISTRITO)) #a lo mejor valdría la pena agregar un bind_rows y juntar todos los meses

#Renombrar variables que aparecen con encabezado numérico. Esto ocurre porque el archivo tiene celdas combianadas, al dividirlas R lee algunos encabezados en blanco y les asigna un número
ebt <- ebt %>% rename('P_SENSI_M<15' = `PERSONAS SENSIBILIZADAS`,
               'P_SENSI_M_15-64' = `...19`,
               'P_SENSI_M=>65' = `...20`,
               'P_SENSI_M' = `...21`,
               'P_SENSI_F<15' = `...22`,
               'P_SENSI_F_15-64' = `...23`,
               'P_SENSI_F=>65' = `...24`,
               'P_SENSI_F' = `...25`,
               'P_SENSI_TOTAL' = `...26`,
               'P_SENSI_TOT_AC' = `...27`,
              'DETERMINANTES SOCIALES-2'  = `...29`,
               'CASAS PROMOCIONADAS' = `CASAS VISITADAS`,
               'CASAS ENCUESTADAS' = `...34`,
               'CASAS AUSENTES' = `...35`,
               'CASAS RENUENTES' = `...36`,
               'CASAS DESHABITADAS' = `...37`,
               'CASAS_VISITADAS_TOT' = `...38`,
               'CASAS_VISITADAS_TOT_AC' = `...39`,
              'AS_COMERCIOS' = `ACTIVOS SENSIBILIZADOS`,
              'AS_CONSULT_ANEXOS-CAPACITADOS-GEO'  = `...41`, 
              'AS_ESCUELAS' = `...42`,
              'AS_ALBERGUES' = `...43`,
              'AS_CAMPO_AGRICOLA' = `...44`,
              'AS_INST_GOBIERNO' = `...45`,
              'AS_CENTRO_COMERCIAL' = `...46`,
              'AS_PLAZA_PUBLICA' = `...47`,
              'AS_IGLESIA' = `...48`,
              'AS_LIDERES_ENCONTRADOS' = `...49`,
              'NOMBRE-DIRECCION-TELEFONO' = `...51`,
              'TEMA ABORDADO (FMRR)' = `FIEBRE MANCHADA POR RICKETTSIA RICKETTSII (FMRR)`,
              'VOLANTES ENTREGADOS FMRR' = `...56`,
              'CARTELES PEGADOS FMRR' = `...57`,
                'ALGORITMOS DE FMRR ENTREGADOS-NESTFORMS-SUIVE' = `...58`,
                'FUMIGACION FMRR' = `...59`,
            'EST_ENTOM_INT_VIV_LARV'  = `...61`,
            'EST_ENTOM_INT_VIV_NINF' = `...62`,
            'EST_ENTOM_INT_VIV_ADUL' = `...63`,
            'EST_ENTOM_INT_VIV_TOT'  = `...64`,
            'EST_ENTOM_EXT_VIV_LARV' = `...65`,
            'EST_ENTOM_EXT_VIV_NINF' = `...66`,
            'EST_ENTOM_EXT_VIV_ADUL' = `...67`,
            'EST_ENTOM_EXT_VIV_TOT'  = `...68`,
            'EST_ENTOM_PAT_FRON_VIV_LARV'  = `...69`,
            'EST_ENTOM_PAT_FRON_VIV_NINF' = `...70`,
            'EST_ENTOM_PAT_FRON_VIV_ADUL' = `...71`,
            'EST_ENTOM_PAT_FRON_VIV_TOT' = `...72`,
            'EST_ENTOM_PAT_POS_VIV_LARV' = `...73`,
            'EST_ENTOM_PAT_POS_VIV_NINF'  = `...74`,
            'EST_ENTOM_PAT_POS_VIV_ADUL' = `...75`,
            'EST_ENTOM_PAT_POS_VIV_TOT' = `...76`,
             'TOTAL GARRAPATAS' = `...77`,
             'TOTAL AC' = `...78`,
            'TEMA ABORDADO (DENGUE)' = `DENGUE`,
            'VOLANTES ENTREGADOS DENGUE' = `...81`,
            'CARTELES PEGADOS DENGUE' =  `...82`,
            'INICIO_SINT_DENGUE' = `...83`,
            'FEBRILES_TOMADOS_M' = `...84`,
            'FEBRILES_TOMADOS_F' = `...85`,
            'FEBRILES_TOMADOS_TOT' = `...86`,
            'FEBRILES_TOMADOS_TOT_AC' = `...87`,
            'CONTROL_LARV_CASAS_T' = `...88`,
            'CONTROL_LARV_CASAS_C' = `...89`,
            'CONTROL_LARV_CASAS_D' = `...90`,
            'CONTROL_LARV_CASAS_R' = `...91`,
            'CONTROL_LARV_CASAS_REV' = `...92`,
            'CONTROL_LARV_CASAS_TOT_AC' = `...93`,
            'CONTROL_LARV_DEPOSITOS_E' = `...94`,
            'CONTROL_LARV_DEPOSITOS_C' = `...95`,
            'CONTROL_LARV_DEPOSITOS_T' = `...96`,
            'CONTROL_LARV_DEPOSITOS_NOT' = `...97`,
            'CONTROL_LARV_DEPOSITOS_REV' = `...98`,
            'CONTROL_LARV_DEPOSITOS_TOT_AC' = `...99`,
            'VAC_ANTIRAB_P-M' = `RABIA - CAMPAÑAS`,
            'VAC_ANTIRAB_P-H' = `...101`,
            'VAC_ANTIRAB_P'= `...102`,
            'VAC_ANTIRAB_G-M' = `...103`,
            'VAC_ANTIRAB_G-H' = `...104`,
            'VAC_ANTIRAB_G' = `...105`,
            'VAC_ANTIRAB_TOT' = `...106`,
            'VAC_ANTIRAB_TOT_AC' = `...107`,
           'DESPARACITACIONES_P-M' = `...108`,
           'DESPARACITACIONES_P-H' = `...109`,
           'DESPARACITACIONES_P' = `...110`,
           'DESPARACITACIONES_G-M' = `...111`,
           'DESPARACITACIONES_G-H'  = `...112`,
           'DESPARACITACIONES_G' = `...113`,
           'DESPARACITACIONES_TOT'  = `...114`,
           'DESPARACITACIONES_TOT_AC'  = `...115`,
          'ESTERILIZACIONES_P-M'  = `...116`,
          'ESTERILIZACIONES_P-H' = `...117`,
          'ESTERILIZACIONES_P' = `...118`,
          'ESTERILIZACIONES_G-M' = `...119`,
          'ESTERILIZACIONES_G-H' = `...120`,
          'ESTERILIZACIONES_G' = `...121`,
          'ESTERILIZACIONES_TOT' = `...122`,
          'ESTERILIZACIONES_TOT_AC' = `...123`,
          'COLONIA CLASIFICADA' = `COLONIA                                                       (RA=RIESGO ALTO / RM=RIESGO MEDIO / RB=RIESGO BAJO / SR=SIN RIESGO)`
            ) %>% 
  select(-c(`...3`, `...8`, `...10`, `...12`, `...14`, `...16`, `...30`, `...32`, `...50`, `...53`, `...55`, `...60`, `...80`, `1. ACONCHI`)) #Como el archivo tiene columnas ocultas, aquí se las quito

#Creación de varibles nuevas

ebt <- ebt %>% mutate(COL_RIESGO = case_when(
  str_detect(`COLONIA CLASIFICADA`,".RB")|str_detect(`COLONIA CLASIFICADA`,". RB") ~ 'BAJO',
  str_detect(`COLONIA CLASIFICADA`,".RM")|str_detect(`COLONIA CLASIFICADA`,". RM") ~ 'MEDIO',
  str_detect(`COLONIA CLASIFICADA`,".RA")|str_detect(`COLONIA CLASIFICADA`,". RA") ~ 'ALTO',
  str_detect(`COLONIA CLASIFICADA`,".SR")|str_detect(`COLONIA CLASIFICADA`,". SR") ~ 'SIN RIESGO',
  T ~ `COLONIA CLASIFICADA`
))

ebt <- ebt %>% mutate(
  DSOC_GRUPO_ETNICO = case_when(
    `DETERMINANTES SOCIALES` == '1. GRUPO ETNICO'|`DETERMINANTES SOCIALES-2` == '1. GRUPO ETNICO'|
      `DETERMINANTES SOCIALES` == 'TODOS: 1, 2' | `DETERMINANTES SOCIALES-2` == 'TODOS: 1, 2' |
      `DETERMINANTES SOCIALES` == 'TODOS: 1 AL 9' | `DETERMINANTES SOCIALES-2` == 'TODOS: 1 AL 9' |
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_MIGRANTE = case_when(
    `DETERMINANTES SOCIALES` == '2. MIGRANTE'|`DETERMINANTES SOCIALES-2` == '2. MIGRANTE'|
      `DETERMINANTES SOCIALES` == 'TODOS: 1, 2' | `DETERMINANTES SOCIALES-2` == 'TODOS: 1, 2'|
      `DETERMINANTES SOCIALES` == 'TODOS: 1 AL 9'| `DETERMINANTES SOCIALES-2` == 'TODOS: 1 AL 9'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_DESB_DRENA_ACUM_BASURA = case_when(
    `DETERMINANTES SOCIALES` == '3. DESBORDE DE DRENAJES / ACUMULACION DE BASURA'|`DETERMINANTES SOCIALES-2` == '3. DESBORDE DE DRENAJES / ACUMULACION DE BASURA'|
      `DETERMINANTES SOCIALES` == 'TODOS: 1 AL 9' |`DETERMINANTES SOCIALES-2` == 'TODOS: 1 AL 9'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14' |
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_FALTA_SANEA_BAS = case_when(
    `DETERMINANTES SOCIALES` == '4. FALTA DE SANEAMIENTO BASICO'|`DETERMINANTES SOCIALES-2` == '4. FALTA DE SANEAMIENTO BASICO'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14' |
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_POBREZA = case_when(
    `DETERMINANTES SOCIALES` == '5. POBREZA'|`DETERMINANTES SOCIALES-2` == '5. POBREZA' |
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_DESEMPLEO = case_when(
    `DETERMINANTES SOCIALES` == '6. DESEMPLEO'|`DETERMINANTES SOCIALES-2` == '6. DESEMPLEO' |
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_FALTA_TEN_RESP_MASC = case_when(
    `DETERMINANTES SOCIALES` == '7. FALTA DE TENENCIA RESPONSABLE DE MASCOTAS'|`DETERMINANTES SOCIALES-2` == '7. FALTA DE TENENCIA RESPONSABLE DE MASCOTAS'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ), 
  DSOC_PERROS_CALLEJ = case_when(
    `DETERMINANTES SOCIALES` == '8. MUCHOS PERROS CALLEJEROS'|`DETERMINANTES SOCIALES-2` == '8. MUCHOS PERROS CALLEJEROS'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_P_SIT_CALLE = case_when(
    `DETERMINANTES SOCIALES` == '9. PERSONAS EN SITUACION DE CALLE'|`DETERMINANTES SOCIALES-2` == '9. PERSONAS EN SITUACION DE CALLE' |
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
   DSOC_NIÑOS_SIN_IR_ESC = case_when(
     `DETERMINANTES SOCIALES` == '10. NIÑOS SIN IR A LA ESCUELA'|`DETERMINANTES SOCIALES-2` == '10. NIÑOS SIN IR A LA ESCUELA'|
       `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_LENOCINIO = case_when(
     `DETERMINANTES SOCIALES` == '11. LENOCINIO'|`DETERMINANTES SOCIALES-2` == '11. LENOCINIO'|
       `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
  DSOC_PRESEN_ADULT_MAYOR = case_when(
    `DETERMINANTES SOCIALES` == '12. PRESENCIA ADULTOS MAYORES'|`DETERMINANTES SOCIALES-2` == '12. PRESENCIA ADULTOS MAYORES'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_VIOL_INTRAFAMILIAR = case_when(
    `DETERMINANTES SOCIALES` == '13. VIOLENCIA INTRAFAMILIAR'|`DETERMINANTES SOCIALES-2` == '13. VIOLENCIA INTRAFAMILIAR'|
      `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
   DSOC_CONS_SUST_PSICOAC = case_when(
     `DETERMINANTES SOCIALES` == '14. CONSUMO DE SUTANCIAS PSICOACTIVAS'|`DETERMINANTES SOCIALES-2` == '14. CONSUMO DE SUTANCIAS PSICOACTIVAS'|
       `DETERMINANTES SOCIALES` == 'TODOS: 3 AL 14' | `DETERMINANTES SOCIALES-2` == 'TODOS: 3 AL 14'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_INST_ELEC_MAL_EDO = case_when(
     `DETERMINANTES SOCIALES` == '15. INSTALACIONES ELECTRICAS EN MAL ESTADO'|`DETERMINANTES SOCIALES-2` == '15. INSTALACIONES ELECTRICAS EN MAL ESTADO' |
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
  DSOC_GATOS_CALLEJ = case_when(
    `DETERMINANTES SOCIALES` == '16. MUCHOS GATOS CALLEJEROS'|`DETERMINANTES SOCIALES-2` == '16. MUCHOS GATOS CALLEJEROS' |
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_VIVIENDA_INFEST_GARRAP = case_when(
    `DETERMINANTES SOCIALES` == '17. VIVIENDAS INFESTADAS DE GARRAPATAS'|`DETERMINANTES SOCIALES-2` == '17. VIVIENDAS INFESTADAS DE GARRAPATAS'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
  DSOC_ABANDONO_MASCOTAS_EXTERNO_A_LA_LOCALIDAD = case_when(
    `DETERMINANTES SOCIALES` == '18. ABANDONO DE MASCOTAS EXTERNO A LA LOCALIDAD'|`DETERMINANTES SOCIALES-2` == '18. ABANDONO DE MASCOTAS EXTERNO A LA LOCALIDAD'|
      `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
    T ~ 'NO'
  ),
   DSOC_ESCASES_AGUA = case_when(
     `DETERMINANTES SOCIALES` == '19. ESCASES DE AGUA'|`DETERMINANTES SOCIALES-2` == '19. ESCASES DE AGUA'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_EXTRANJEROS = case_when(
     `DETERMINANTES SOCIALES` == '20. EXTRANJEROS'|`DETERMINANTES SOCIALES-2` == '20. EXTRANJEROS' |
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_HACINAMIENTO_ANIMAL = case_when(
     `DETERMINANTES SOCIALES` == '21. HACINAMIENTO ANIMAL'|`DETERMINANTES SOCIALES-2` == '21. HACINAMIENTO ANIMAL' |
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_HACINAMIENTO_HUMANO = case_when(
     `DETERMINANTES SOCIALES` == '22. HACINAMIENTO HUMANO'|`DETERMINANTES SOCIALES-2` == '22. HACINAMIENTO HUMANO' |
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_FALTA_TELECOM = case_when(
     `DETERMINANTES SOCIALES` == '23. FALTA DE TELECOMUNICACIONES'|`DETERMINANTES SOCIALES-2` == '23. FALTA DE TELECOMUNICACIONES'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_CALLES_SIN_PAVIM = case_when(
     `DETERMINANTES SOCIALES` == '24. CALLES SIN PAVIMENTAR'|`DETERMINANTES SOCIALES-2` == '24. CALLES SIN PAVIMENTAR' |
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   ),
   DSOC_CONTAM_AUDITIVA_POR_PERROS = case_when(
     `DETERMINANTES SOCIALES` == '25. CONTAMINACION AUDITIVA POR PERROS'|`DETERMINANTES SOCIALES-2` == '25. CONTAMINACION AUDITIVA POR PERROS'|
       `DETERMINANTES SOCIALES` == 'TODOS' | `DETERMINANTES SOCIALES-2` == 'TODOS' ~ 'SI',
     T ~ 'NO'
   )
  ) %>% 
  mutate(`NUMERO DE INTERVENCIONES TRANSVERSALES` = case_when(
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'UN PROGRAMA C/ACCIONES POLIVALENTES' | `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'UN PROGRAMA C/ACCIONES ESPECIALIZADAS' ~ '1',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'DOS PROGRAMAS' ~ '2',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'TRES PROGRAMAS' ~ '3',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'CUATRO PROGRAMAS' ~ '4',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'CINCO PROGRAMAS' ~ '5',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'SEIS PROGRAMAS' ~ '6',
    `NUMERO DE INTERVENCIONES TRANSVERSALES` == 'SIETE PROGRAMAS' ~ '7',
    T ~ `NUMERO DE INTERVENCIONES TRANSVERSALES`
    ),
    `TEMA ABORDADO (FMRR)` = case_when(
      `TEMA ABORDADO (FMRR)` == 'APLICA' ~ 'SI',
      `TEMA ABORDADO (FMRR)` == 'NO APLICA' ~ 'NO',
      T ~ `TEMA ABORDADO (FMRR)`
    ),
    `TEMA ABORDADO (DENGUE)` = case_when(
      `TEMA ABORDADO (DENGUE)` == 'APLICA' ~ 'SI',
      `TEMA ABORDADO (DENGUE)` == 'NO APLICA' ~ 'NO',
      T ~ `TEMA ABORDADO (DENGUE)`
    )
    ) %>% 
  select(-c(`DETERMINANTES SOCIALES`, `DETERMINANTES SOCIALES-2`)) %>% 
  select(c(FECHA, DISTRITO, MUNICIPIO,	LOCALIDAD, `COLONIA CLASIFICADA`, COL_RIESGO, LUGAR, MOTIVO,`TIPO DE INTERVENCION`,	`ESCUADRON QUE LO REALIZO`,`HORAS DE PERIFONEO`,`P_SENSI_M<15`,
`P_SENSI_M_15-64`, `P_SENSI_M=>65`, `P_SENSI_M`,	`P_SENSI_F<15`, `P_SENSI_F_15-64`, `P_SENSI_F=>65`, `P_SENSI_F`, `P_SENSI_TOTAL`, `P_SENSI_TOT_AC`, DSOC_GRUPO_ETNICO, DSOC_MIGRANTE, 
DSOC_DESB_DRENA_ACUM_BASURA, DSOC_FALTA_SANEA_BAS, DSOC_POBREZA, DSOC_DESEMPLEO, DSOC_FALTA_TEN_RESP_MASC, DSOC_PERROS_CALLEJ,	DSOC_P_SIT_CALLE,	DSOC_NIÑOS_SIN_IR_ESC,	DSOC_LENOCINIO,
DSOC_PRESEN_ADULT_MAYOR,	DSOC_VIOL_INTRAFAMILIAR,	DSOC_CONS_SUST_PSICOAC,	DSOC_INST_ELEC_MAL_EDO,	DSOC_GATOS_CALLEJ,	DSOC_VIVIENDA_INFEST_GARRAP,	DSOC_ABANDONO_MASCOTAS_EXTERNO_A_LA_LOCALIDAD,	
DSOC_ESCASES_AGUA,	DSOC_EXTRANJEROS,	DSOC_HACINAMIENTO_ANIMAL,	DSOC_HACINAMIENTO_HUMANO,	DSOC_FALTA_TELECOM,	DSOC_CALLES_SIN_PAVIM,	DSOC_CONTAM_AUDITIVA_POR_PERROS,
`DATOS EPIDEMIOLOGICOS`, `CASAS PROMOCIONADAS`, `CASAS ENCUESTADAS`, `CASAS AUSENTES`, `CASAS RENUENTES`, `CASAS DESHABITADAS`, `CASAS_VISITADAS_TOT`, `CASAS_VISITADAS_TOT_AC`, `AS_COMERCIOS`,
`AS_CONSULT_ANEXOS-CAPACITADOS-GEO`, `AS_ESCUELAS`, `AS_ALBERGUES`, `AS_CAMPO_AGRICOLA`, `AS_INST_GOBIERNO`, `AS_CENTRO_COMERCIAL`, `AS_PLAZA_PUBLICA`, `AS_IGLESIA`, `AS_LIDERES_ENCONTRADOS`, 
`NOMBRE-DIRECCION-TELEFONO`, `NUMERO DE INTERVENCIONES TRANSVERSALES`, `TEMA ABORDADO (FMRR)`, `VOLANTES ENTREGADOS FMRR`, `CARTELES PEGADOS FMRR`,`ALGORITMOS DE FMRR ENTREGADOS-NESTFORMS-SUIVE`,
`FUMIGACION FMRR`, `EST_ENTOM_INT_VIV_LARV`, `EST_ENTOM_INT_VIV_NINF`, `EST_ENTOM_INT_VIV_ADUL`, `EST_ENTOM_INT_VIV_TOT`, `EST_ENTOM_EXT_VIV_LARV`, `EST_ENTOM_EXT_VIV_NINF`,
`EST_ENTOM_EXT_VIV_ADUL`, `EST_ENTOM_EXT_VIV_TOT`, EST_ENTOM_PAT_FRON_VIV_LARV, EST_ENTOM_PAT_FRON_VIV_NINF, EST_ENTOM_PAT_FRON_VIV_ADUL, EST_ENTOM_PAT_FRON_VIV_TOT, EST_ENTOM_PAT_POS_VIV_LARV,
EST_ENTOM_PAT_POS_VIV_NINF, EST_ENTOM_PAT_POS_VIV_ADUL, EST_ENTOM_PAT_POS_VIV_TOT, `TOTAL GARRAPATAS`, `TOTAL AC`, `TEMA ABORDADO (DENGUE)`, `VOLANTES ENTREGADOS DENGUE`, `CARTELES PEGADOS DENGUE`,
INICIO_SINT_DENGUE, FEBRILES_TOMADOS_M, FEBRILES_TOMADOS_F, FEBRILES_TOMADOS_TOT, FEBRILES_TOMADOS_TOT_AC, CONTROL_LARV_CASAS_T, CONTROL_LARV_CASAS_C, CONTROL_LARV_CASAS_D, CONTROL_LARV_CASAS_R,
CONTROL_LARV_CASAS_REV, CONTROL_LARV_CASAS_TOT_AC, CONTROL_LARV_DEPOSITOS_E, CONTROL_LARV_DEPOSITOS_C, CONTROL_LARV_DEPOSITOS_T, CONTROL_LARV_DEPOSITOS_NOT, CONTROL_LARV_DEPOSITOS_REV, CONTROL_LARV_DEPOSITOS_TOT_AC,
`VAC_ANTIRAB_P-M`, `VAC_ANTIRAB_P-H`, VAC_ANTIRAB_P, `VAC_ANTIRAB_G-M`, `VAC_ANTIRAB_G-H`, VAC_ANTIRAB_G, VAC_ANTIRAB_TOT, VAC_ANTIRAB_TOT_AC, `DESPARACITACIONES_P-M`, `DESPARACITACIONES_P-H`, DESPARACITACIONES_P,
`DESPARACITACIONES_G-M`, `DESPARACITACIONES_G-H`, DESPARACITACIONES_G, DESPARACITACIONES_TOT, DESPARACITACIONES_TOT_AC, `ESTERILIZACIONES_P-M`, `ESTERILIZACIONES_P-H`, ESTERILIZACIONES_P,
`ESTERILIZACIONES_G-M`, `ESTERILIZACIONES_G-H`,	ESTERILIZACIONES_G, ESTERILIZACIONES_TOT, ESTERILIZACIONES_TOT_AC)) #aquí ordeno las columnas a como aparecen en el documento original


openxlsx::write.xlsx(ebt, 'ebt.xlsx')







